version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    networks:
      - chatbot-network
    environment:
      DATABASE_URL: postgresql://user:password@database:5432/chatbotdb
      REDIS_URL: redis://redis:6379/0

  database:
    image: postgres:17.3
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbotdb
    ports:
      - "5433:5432"
    networks:
      - chatbot-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6380:6379"
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge

volumes:
  postgres_data:
