"""remove contact from conversation

Revision ID: 0407e4efaeaf
Revises: 9524bed6dd7d
Create Date: 2025-03-24 23:48:23.529107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0407e4efaeaf'
down_revision: Union[str, None] = '9524bed6dd7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_contact_id_fkey', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'contact_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('conversations_contact_id_fkey', 'conversations', 'contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###
