"""Add ping pong circuit breaker fields to Conversation

Revision ID: 1063f8d5f5d9
Revises: 43abac917746
Create Date: 2025-06-27 15:40:33.354668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1063f8d5f5d9'
down_revision: Union[str, None] = '43abac917746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('ping_pong_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('conversations', sa.Column('last_agent_message_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'last_agent_message_timestamp')
    op.drop_column('conversations', 'ping_pong_count')
    # ### end Alembic commands ###
