"""Add simulations, simulation_messages, and simulation_events tables

Revision ID: 1239c30c45d8
Revises: da3013a524cc
Create Date: 2025-04-21 22:58:19.960158

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1239c30c45d8"
down_revision: Union[str, None] = "da3013a524cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_profile_id", sa.UUID(), nullable=True),
        sa.Column("persona_definition", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING", "COMPLETED", "FAILED", "TIMEOUT", name="simulationstatusenum"
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "SALE_COMPLETED",
                "LEAD_QUALIFIED",
                "INFO_OBTAINED",
                "USER_GAVE_UP",
                "AI_USED_FALLBACK",
                "TURN_LIMIT_REACHED",
                "AI_ERROR",
                "SIMULATION_ERROR",
                name="simulationoutcomeenum",
            ),
            nullable=True,
        ),
        sa.Column("turn_count", sa.Integer(), nullable=True),
        sa.Column("simulation_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("fallback_used", sa.Boolean(), nullable=True),
        sa.Column("evaluation_metrics", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_profile_id"], ["company_profiles.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulations_company_profile_id"),
        "simulations",
        ["company_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simulations_outcome"), "simulations", ["outcome"], unique=False
    )
    op.create_index(
        op.f("ix_simulations_status"), "simulations", ["status"], unique=False
    )

    op.create_table(
        "simulation_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("simulation_id", sa.UUID(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "event_type",
            sa.Enum(
                "SIMULATION_START",
                "TURN_START",
                "USER_MESSAGE_SENT",
                "AI_RESPONSE_RECEIVED",
                "AI_FALLBACK_DETECTED",
                "PERSONA_OBJECTIVE_MET",
                "PERSONA_GAVE_UP",
                "RULE_VIOLATION_DETECTED",
                "LLM_EVALUATION_TRIGGERED",
                "AI_PROCESSING_ERROR",
                "SIMULATION_ENGINE_ERROR",
                "TURN_LIMIT_WARNING",
                "SIMULATION_END",
                name="simulationeventtypeenum",
            ),
            nullable=False,
        ),
        sa.Column("turn_number", sa.Integer(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"], ["simulations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulation_events_event_type"),
        "simulation_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simulation_events_simulation_id"),
        "simulation_events",
        ["simulation_id"],
        unique=False,
    )

    op.create_table(
        "simulation_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("simulation_id", sa.UUID(), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("USER", "ASSISTANT", "SYSTEM", name="simulationmessageroleenum"),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("original_message_id", sa.UUID(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"], ["simulations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulation_messages_simulation_id"),
        "simulation_messages",
        ["simulation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_simulation_messages_simulation_id"), table_name="simulation_messages"
    )
    op.drop_table("simulation_messages")
    op.drop_index(
        op.f("ix_simulation_events_simulation_id"), table_name="simulation_events"
    )
    op.drop_index(
        op.f("ix_simulation_events_event_type"), table_name="simulation_events"
    )
    op.drop_table("simulation_events")
    op.drop_index(op.f("ix_simulations_status"), table_name="simulations")
    op.drop_index(op.f("ix_simulations_outcome"), table_name="simulations")
    op.drop_index(op.f("ix_simulations_company_profile_id"), table_name="simulations")
    op.drop_table("simulations")
    # ### end Alembic commands ###
