"""add account_id, channel_id, channel_type to inbox unique constraint

Revision ID: 1b205b5284d2
Revises: abc42
Create Date: 2025-03-28 17:11:40.062297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b205b5284d2'
down_revision: Union[str, None] = 'abc42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('account_inbox_account_id_channel_id_channe_type_unique', 'inboxes', ['account_id', 'channel_id', 'channel_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_inbox_account_id_channel_id_channe_type_unique', 'inboxes', type_='unique')
    # ### end Alembic commands ###
