"""add is_whatsapp and is_whatsapp_business

Revision ID: 2b5899baa957
Revises: 728f72dbb085
Create Date: 2025-04-11 17:29:57.000546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5899baa957'
down_revision: Union[str, None] = '728f72dbb085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('is_whatsapp_business', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('is_whatsapp', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'is_whatsapp')
    op.drop_column('contacts', 'is_whatsapp_business')
    # ### end Alembic commands ###
