"""add scheduling_min_notice_hours to company_profile

Revision ID: 34da9871235d
Revises: 3256a47b6090
Create Date: 2025-06-23 18:11:08.434213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34da9871235d"
down_revision: Union[str, None] = "3256a47b6090"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_profiles",
        sa.Column(
            "scheduling_min_notice_hours",
            sa.Float(),
            server_default=sa.text("2.0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company_profiles", "scheduling_min_notice_hours")
    # ### end Alembic commands ###
