"""use string 255 for verify token

Revision ID: 36c9c7b0849e
Revises: 2bc063ca32e2
Create Date: 2025-05-13 00:52:59.751181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36c9c7b0849e'
down_revision: Union[str, None] = '2bc063ca32e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'is_bot_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('knowledge_chunks', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('personas', 'information_needed',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_comment="List of dicts: [{'entity': 'x', 'attribute': 'y'}] - Contextual info persona seeks.",
               existing_nullable=False)
    op.alter_column('personas', 'success_criteria',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_comment='List of strings defining success (often empty now).',
               existing_nullable=False)
    op.alter_column('personas', 'failure_criteria',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text('\'["event:ai_fallback_detected", "turn_count > 10"]\'::jsonb'),
               existing_comment='List of strings defining failure.',
               existing_nullable=False)
    op.alter_column('whatsapp_cloud_configs', 'webhook_verify_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='The verify token configured in the Meta App for webhook verification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsapp_cloud_configs', 'webhook_verify_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='The verify token configured in the Meta App for webhook verification')
    op.alter_column('personas', 'failure_criteria',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_comment='List of strings defining failure.',
               existing_nullable=False)
    op.alter_column('personas', 'success_criteria',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_comment='List of strings defining success (often empty now).',
               existing_nullable=False)
    op.alter_column('personas', 'information_needed',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_comment="List of dicts: [{'entity': 'x', 'attribute': 'y'}] - Contextual info persona seeks.",
               existing_nullable=False)
    op.alter_column('knowledge_chunks', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('conversations', 'is_bot_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
