"""add accepted payment methods

Revision ID: 39677f86a2b5
Revises: 003c78705774
Create Date: 2025-06-05 22:30:05.016814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39677f86a2b5"
down_revision: Union[str, None] = "003c78705774"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_profiles",
        sa.Column(
            "accepted_payment_methods",
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'[]'::json"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company_profiles", "accepted_payment_methods")
    # ### end Alembic commands ###
