"""Add Persona model and relationship to Contact

Revision ID: 3aed2d485d9a
Revises: d38e48325068
Create Date: 2025-05-02 22:27:53.789562

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3aed2d485d9a"
down_revision: Union[str, None] = "d38e48325068"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("persona_id", sa.String(), nullable=False),
        sa.Column("simulation_contact_identifier", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("initial_message", sa.Text(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column(
            "information_needed",
            sa.JSON(),
            nullable=False,
            comment="List of dicts: [{'entity': 'x', 'attribute': 'y'}]",
        ),
        sa.Column(
            "info_attribute_to_question_template",
            sa.JSON(),
            nullable=False,
            comment="Dict: {'attribute': 'template {entity} ?'}",
        ),
        sa.Column(
            "success_criteria",
            sa.JSON(),
            nullable=False,
            comment="List of strings, e.g. ['state:all_info_extracted']",
        ),
        sa.Column(
            "failure_criteria",
            sa.JSON(),
            nullable=False,
            comment="List of strings, e.g. ['event:ai_fallback_detected']",
        ),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("persona_id", name="uq_persona_persona_id"),
        sa.UniqueConstraint(
            "simulation_contact_identifier", name="uq_persona_contact_identifier"
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_personas_simulation_contact_identifier"), table_name="personas"
    )
    op.drop_index(op.f("ix_personas_persona_id"), table_name="personas")
    op.drop_index(op.f("ix_personas_contact_id"), table_name="personas")
    op.drop_table("personas")
    # ### end Alembic commands ###
