"""use jsonb on the additional attributes

Revision ID: 433626211b48
Revises: b744e27df580
Create Date: 2025-04-03 23:06:09.253522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '433626211b48'
down_revision: Union[str, None] = 'b744e27df580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'additional_attributes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('conversations_account_id_index', table_name='conversations')
    op.drop_index('conversations_contact_inbox_id_index', table_name='conversations')
    op.create_index('idx_conversations_account_id', 'conversations', ['account_id'], unique=False)
    op.create_index('idx_conversations_contact_inbox_id', 'conversations', ['contact_inbox_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_conversations_contact_inbox_id', table_name='conversations')
    op.drop_index('idx_conversations_account_id', table_name='conversations')
    op.create_index('conversations_contact_inbox_id_index', 'conversations', ['contact_inbox_id'], unique=False)
    op.create_index('conversations_account_id_index', 'conversations', ['account_id'], unique=False)
    op.alter_column('conversations', 'additional_attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
