"""Add set null on cascade for inbox delete on message

Revision ID: 43abac917746
Revises: a887fbb791fb
Create Date: 2025-06-27 03:16:44.792436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43abac917746'
down_revision: Union[str, None] = 'a887fbb791fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_inbox_whatsapp_cloud_config_id', 'inboxes', type_='foreignkey')
    op.create_foreign_key('fk_inbox_whatsapp_cloud_config_id', 'inboxes', 'whatsapp_cloud_configs', ['whatsapp_cloud_config_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_inbox_whatsapp_cloud_config_id', 'inboxes', type_='foreignkey')
    op.create_foreign_key('fk_inbox_whatsapp_cloud_config_id', 'inboxes', 'whatsapp_cloud_configs', ['whatsapp_cloud_config_id'], ['id'])
    # ### end Alembic commands ###
