"""add deleted_at column and add indexes to improve search

Revision ID: 4535c83d2f04
Revises: cd5067c4f5bc
Create Date: 2025-04-08 22:42:41.204889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4535c83d2f04'
down_revision: Union[str, None] = 'cd5067c4f5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('contacts_account_id_identifier_unique', 'contacts', type_='unique')
    op.drop_constraint('contacts_email_account_id_unique', 'contacts', type_='unique')
    op.drop_constraint('contacts_pubsub_token_unique', 'contacts', type_='unique')
    op.create_index('ix_contacts_account_id_active', 'contacts', ['account_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_contacts_account_id_identifier_active_unique', 'contacts', ['account_id', 'identifier'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_contacts_email_account_id_active_unique', 'contacts', ['account_id', 'email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND email IS NOT NULL'))
    op.create_index('ix_contacts_email_active', 'contacts', ['email'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND email IS NOT NULL'))
    op.create_index('ix_contacts_name_gin_trgm', 'contacts', ['phone_number'], unique=False, postgresql_using='gin', postgresql_ops={'phone_number': 'gin_trgm_ops'})
    op.create_index('ix_contacts_phone_number_active', 'contacts', ['phone_number'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_contacts_pubsub_token_active_unique', 'contacts', ['pubsub_token'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND pubsub_token IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_pubsub_token_active_unique', table_name='contacts', postgresql_where=sa.text('deleted_at IS NULL AND pubsub_token IS NOT NULL'))
    op.drop_index('ix_contacts_phone_number_active', table_name='contacts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_contacts_name_gin_trgm', table_name='contacts', postgresql_using='gin', postgresql_ops={'phone_number': 'gin_trgm_ops'})
    op.drop_index('ix_contacts_email_active', table_name='contacts', postgresql_where=sa.text('deleted_at IS NULL AND email IS NOT NULL'))
    op.drop_index('ix_contacts_email_account_id_active_unique', table_name='contacts', postgresql_where=sa.text('deleted_at IS NULL AND email IS NOT NULL'))
    op.drop_index('ix_contacts_account_id_identifier_active_unique', table_name='contacts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_contacts_account_id_active', table_name='contacts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint('contacts_pubsub_token_unique', 'contacts', ['pubsub_token'])
    op.create_unique_constraint('contacts_email_account_id_unique', 'contacts', ['email', 'account_id'])
    op.create_unique_constraint('contacts_account_id_identifier_unique', 'contacts', ['account_id', 'identifier'])
    op.drop_column('contacts', 'deleted_at')
    # ### end Alembic commands ###
