"""add status, unread_agent_count ,is_bot_active

Revision ID: 4a8f87ad3ce3
Revises: 37c0804f34de
Create Date: 2025-04-11 23:29:53.582966

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a8f87ad3ce3"
down_revision: Union[str, None] = "37c0804f34de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

conversation_status_enum = sa.Enum(
    "OPEN", "HUMAN_ACTIVE", "CLOSED", "PENDING", name="conversation_status_enum"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conversation_status_enum.create(op.get_bind())

    op.add_column(
        "conversations",
        sa.Column(
            "unread_agent_count",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Count of unread messages for the agent since last interaction/read",
        ),
    )
    op.add_column(
        "conversations",
        sa.Column(
            "is_bot_active", sa.Boolean(), server_default="False", nullable=False
        ),
    )

    op.alter_column(
        "conversations",
        "status",
        existing_type=sa.VARCHAR(length=50),
        type_=conversation_status_enum,
        postgresql_using="status::conversation_status_enum",
        comment="Current status of the conversation regarding human interaction",
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_conversations_status"), "conversations", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversations_status"), table_name="conversations")
    op.alter_column(
        "conversations",
        "status",
        existing_type=sa.Enum(
            "PENDING", "HUMAN_ACTIVE", "CLOSED", name="conversation_status_enum"
        ),
        type_=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Current status of the conversation regarding human interaction",
        existing_nullable=False,
    )
    op.drop_column("conversations", "is_bot_active")
    op.drop_column("conversations", "unread_agent_count")
    # ### end Alembic commands ###
