"""add stripe customer id to account

Revision ID: 4d0e498b724d
Revises: 3ae78fa722f3
Create Date: 2025-05-22 21:49:58.956276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0e498b724d'
down_revision: Union[str, None] = '3ae78fa722f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_accounts_stripe_customer_id'), 'accounts', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_stripe_customer_id'), table_name='accounts')
    op.drop_column('accounts', 'stripe_customer_id')
    # ### end Alembic commands ###
