"""add last_message_at to conversations

Revision ID: 4d3e94d2643c
Revises: 0407e4efaeaf
Create Date: 2025-03-25 09:38:05.798310

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d3e94d2643c"
down_revision: Union[str, None] = "0407e4efaeaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations", sa.Column("last_message_at", sa.DateTime(), nullable=True)
    )
    op.alter_column(
        "conversations",
        "status",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.drop_constraint(
        "conversations_account_id_display_id_unique", "conversations", type_="unique"
    )
    op.create_index(
        op.f("ix_conversations_last_message_at"),
        "conversations",
        ["last_message_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversations_last_message_at"), table_name="conversations")
    op.create_unique_constraint(
        "conversations_account_id_display_id_unique",
        "conversations",
        ["account_id", "display_id"],
    )
    op.alter_column(
        "conversations",
        "status",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_column("conversations", "last_message_at")
    # ### end Alembic commands ###
