"""Add booking_horizon_days to company_profiles

Revision ID: 55651831bd92
Revises: e89b307cfcb4
Create Date: 2025-06-29 00:48:56.296698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55651831bd92'
down_revision: Union[str, None] = 'e89b307cfcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profiles', sa.Column('booking_horizon_days', sa.Integer(), server_default=sa.text('7'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_profiles', 'booking_horizon_days')
    # ### end Alembic commands ###
