"""add availability_rules to the company profile

Revision ID: 64552f9e0591
Revises: 89f3274ed1ab
Create Date: 2025-06-19 19:48:33.917695

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64552f9e0591"
down_revision: Union[str, None] = "89f3274ed1ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_profiles", sa.Column("availability_rules", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company_profiles", "availability_rules")
    # ### end Alembic commands ###
