"""Add is_simulation to the messages

Revision ID: 7dc4950abc22
Revises: ce98cb1386bf
Create Date: 2025-04-29 03:37:51.769267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc4950abc22'
down_revision: Union[str, None] = 'ce98cb1386bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_simulation', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_messages_is_simulation'), 'messages', ['is_simulation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_is_simulation'), table_name='messages')
    op.drop_column('messages', 'is_simulation')
    # ### end Alembic commands ###
