"""Add is_simulation flag to Inbox, Contact, Conversation

Revision ID: 82fa6c556fae
Revises: 9f36e4892390
Create Date: 2025-04-29 01:06:56.618733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fa6c556fae'
down_revision: Union[str, None] = '9f36e4892390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('is_simulation', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_contacts_is_simulation'), 'contacts', ['is_simulation'], unique=False)
    op.add_column('conversations', sa.Column('is_simulation', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_conversations_is_simulation'), 'conversations', ['is_simulation'], unique=False)
    op.add_column('inboxes', sa.Column('is_simulation', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_inboxes_is_simulation'), 'inboxes', ['is_simulation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inboxes_is_simulation'), table_name='inboxes')
    op.drop_column('inboxes', 'is_simulation')
    op.drop_index(op.f('ix_conversations_is_simulation'), table_name='conversations')
    op.drop_column('conversations', 'is_simulation')
    op.drop_index(op.f('ix_contacts_is_simulation'), table_name='contacts')
    op.drop_column('contacts', 'is_simulation')
    # ### end Alembic commands ###
