"""make channel_id string

Revision ID: 84f214006cde
Revises: d95bdcd2f6f3
Create Date: 2025-03-24 21:51:31.785438

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84f214006cde"
down_revision: Union[str, None] = "d95bdcd2f6f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inboxes",
        "channel_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=255),
        existing_nullable=False,
    )

    op.alter_column(
        "conversations",
        "status",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inboxes",
        "channel_id",
        existing_type=sa.String(length=255),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )

    op.alter_column(
        "conversations",
        "status",
        existing_type=sa.String(length=255),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
