"""refact the bot agent models

Revision ID: 85c035cf497d
Revises: 1239c30c45d8
Create Date: 2025-04-25 21:58:04.663519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85c035cf497d"
down_revision: Union[str, None] = "1239c30c45d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agent_bot_inboxes", "inbox_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "agent_bot_inboxes", "agent_bot_id", existing_type=sa.UUID(), nullable=False
    )
    op.create_index(
        op.f("ix_agent_bot_inboxes_agent_bot_id"),
        "agent_bot_inboxes",
        ["agent_bot_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_agent_bot_inboxes_account_inbox",
        "agent_bot_inboxes",
        ["account_id", "inbox_id"],
    )
    op.drop_constraint(
        "agent_bot_inboxes_inbox_id_fkey", "agent_bot_inboxes", type_="foreignkey"
    )
    op.drop_constraint(
        "agent_bot_inboxes_account_id_fkey", "agent_bot_inboxes", type_="foreignkey"
    )
    op.drop_constraint(
        "agent_bot_inboxes_agent_bot_id_fkey", "agent_bot_inboxes", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "agent_bot_inboxes", "inboxes", ["inbox_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "agent_bot_inboxes",
        "agent_bots",
        ["agent_bot_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "agent_bot_inboxes",
        "accounts",
        ["account_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("agent_bot_inboxes", "status")
    op.add_column("agent_bots", sa.Column("account_id", sa.UUID(), nullable=False))
    op.add_column("agent_bots", sa.Column("first_message", sa.Text(), nullable=True))
    op.add_column("agent_bots", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("agent_bots", sa.Column("use_rag", sa.Boolean(), nullable=False))
    op.alter_column(
        "agent_bots", "name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.create_index(
        op.f("ix_agent_bots_account_id"), "agent_bots", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_bots_is_active"), "agent_bots", ["is_active"], unique=False
    )
    op.create_foreign_key(
        None, "agent_bots", "accounts", ["account_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("agent_bots", "description")
    op.drop_column("agent_bots", "outgoing_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_bots",
        sa.Column(
            "outgoing_url", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "agent_bots",
        sa.Column(
            "description", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "agent_bots", type_="foreignkey")
    op.drop_index(op.f("ix_agent_bots_is_active"), table_name="agent_bots")
    op.drop_index(op.f("ix_agent_bots_account_id"), table_name="agent_bots")
    op.alter_column(
        "agent_bots", "name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_column("agent_bots", "use_rag")
    op.drop_column("agent_bots", "is_active")
    op.drop_column("agent_bots", "first_message")
    op.drop_column("agent_bots", "account_id")
    op.add_column(
        "agent_bot_inboxes",
        sa.Column("status", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "agent_bot_inboxes", type_="foreignkey")
    op.drop_constraint(None, "agent_bot_inboxes", type_="foreignkey")
    op.drop_constraint(None, "agent_bot_inboxes", type_="foreignkey")
    op.create_foreign_key(
        "agent_bot_inboxes_agent_bot_id_fkey",
        "agent_bot_inboxes",
        "agent_bots",
        ["agent_bot_id"],
        ["id"],
    )
    op.create_foreign_key(
        "agent_bot_inboxes_account_id_fkey",
        "agent_bot_inboxes",
        "accounts",
        ["account_id"],
        ["id"],
    )
    op.create_foreign_key(
        "agent_bot_inboxes_inbox_id_fkey",
        "agent_bot_inboxes",
        "inboxes",
        ["inbox_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_agent_bot_inboxes_account_inbox", "agent_bot_inboxes", type_="unique"
    )
    op.drop_index(
        op.f("ix_agent_bot_inboxes_agent_bot_id"), table_name="agent_bot_inboxes"
    )
    op.alter_column(
        "agent_bot_inboxes", "agent_bot_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "agent_bot_inboxes", "inbox_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
