"""add sent_at and direction to message 

Revision ID: 895e414822f6
Revises: abc42
Create Date: 2025-03-25 18:24:49.379940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895e414822f6'
down_revision: Union[str, None] = 'abc42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('direction', sa.String(length=50), nullable=False))
    op.add_column('messages', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.create_index('messages_sent_at_index', 'messages', ['sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('messages_sent_at_index', table_name='messages')
    op.drop_column('messages', 'sent_at')
    op.drop_column('messages', 'direction')
    # ### end Alembic commands ###
