"""add scheduling fileds

Revision ID: 89f3274ed1ab
Revises: bd578b560387
Create Date: 2025-06-19 02:24:47.374484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89f3274ed1ab"
down_revision: Union[str, None] = "bd578b560387"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_profiles",
        sa.Column(
            "is_scheduling_enabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "company_profiles",
        sa.Column("scheduling_calendar_id", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company_profiles", "scheduling_calendar_id")
    op.drop_column("company_profiles", "is_scheduling_enabled")
    # ### end Alembic commands ###
