"""Add bot_agent_id to the messages model

Revision ID: 8fc3080234b6
Revises: 36c9c7b0849e
Create Date: 2025-05-19 23:58:12.834992

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8fc3080234b6"
down_revision: Union[str, None] = "36c9c7b0849e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("bot_agent_id", sa.UUID(), nullable=True))
    op.create_index(
        "idx_messages_bot_agent_id_index", "messages", ["bot_agent_id"], unique=False
    )
    op.create_foreign_key(None, "messages", "bot_agents", ["bot_agent_id"], ["id"])
    op.drop_column("messages", "message_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "message_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_index("idx_messages_bot_agent_id_index", table_name="messages")
    op.drop_column("messages", "bot_agent_id")
    # ### end Alembic commands ###
