"""make contact_id and contact_inbox required in conversation

Revision ID: 9524bed6dd7d
Revises: 84f214006cde
Create Date: 2025-03-24 23:26:06.256302

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9524bed6dd7d"
down_revision: Union[str, None] = "84f214006cde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversations", "contact_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "conversations", "contact_inbox_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "conversations", "display_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversations", "display_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "conversations", "contact_inbox_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "conversations", "contact_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
