"""create the gin index

Revision ID: a478bba84cd7
Revises: 433626211b48
Create Date: 2025-04-03 23:11:30.783591

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a478bba84cd7"
down_revision: Union[str, None] = "433626211b48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.create_index(
        "ix_conv_addt_attrs_contact_name_gin_trgm",
        "conversations",
        [sa.text("(additional_attributes->>'contact_name') gin_trgm_ops")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_conv_addt_attrs_phone_number_gin_trgm",
        "conversations",
        [sa.text("(additional_attributes->>'phone_number') gin_trgm_ops")],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_conv_addt_attrs_phone_number_gin_trgm",
        table_name="conversations",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_conv_addt_attrs_contact_name_gin_trgm",
        table_name="conversations",
        postgresql_using="gin",
    )
    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")
    # ### end Alembic commands ###
