"""Initial migration

Revision ID: a7baf7f8a043
Revises: 41ea7b4c1cfb
Create Date: 2025-02-20 21:06:40.765512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7baf7f8a043'
down_revision: Union[str, None] = '41ea7b4c1cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
