"""add import jobs model

Revision ID: a97914f920a6
Revises: ff61c6f05927
Create Date: 2025-04-09 19:44:11.342933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97914f920a6'
down_revision: Union[str, None] = 'ff61c6f05927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('arq_task_id', sa.String(), nullable=True, comment='ID returned by ARQ upon enqueueing'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='import_job_status_enum'), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_account_id'), 'import_jobs', ['account_id'], unique=False)
    op.create_index(op.f('ix_import_jobs_arq_task_id'), 'import_jobs', ['arq_task_id'], unique=False)
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_arq_task_id'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_account_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
