"""create the gin index on the messages table

Revision ID: b84c69aae1a6
Revises: a478bba84cd7
Create Date: 2025-04-03 23:16:37.297215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84c69aae1a6'
down_revision: Union[str, None] = 'a478bba84cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('messages_account_id_index', table_name='messages')
    op.drop_index('messages_contact_id_index', table_name='messages')
    op.drop_index('messages_conversation_id_index', table_name='messages')
    op.drop_index('messages_inbox_id_index', table_name='messages')
    op.drop_index('messages_sent_at_index', table_name='messages')
    op.drop_index('messages_source_id_index', table_name='messages')
    op.drop_index('messages_user_id_index', table_name='messages')
    op.create_index('idx_messages_account_id_index', 'messages', ['account_id'], unique=False)
    op.create_index('idx_messages_contact_id_index', 'messages', ['contact_id'], unique=False)
    op.create_index('idx_messages_conversation_id_index', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_messages_inbox_id_index', 'messages', ['inbox_id'], unique=False)
    op.create_index('idx_messages_sent_at_index', 'messages', ['sent_at'], unique=False)
    op.create_index('idx_messages_source_id_index', 'messages', ['source_id'], unique=False)
    op.create_index('idx_messages_user_id_index', 'messages', ['user_id'], unique=False)
    op.create_index('ix_messages_content_gin_trgm', 'messages', [sa.text('(content) gin_trgm_ops')], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_content_gin_trgm', table_name='messages', postgresql_using='gin')
    op.drop_index('idx_messages_user_id_index', table_name='messages')
    op.drop_index('idx_messages_source_id_index', table_name='messages')
    op.drop_index('idx_messages_sent_at_index', table_name='messages')
    op.drop_index('idx_messages_inbox_id_index', table_name='messages')
    op.drop_index('idx_messages_conversation_id_index', table_name='messages')
    op.drop_index('idx_messages_contact_id_index', table_name='messages')
    op.drop_index('idx_messages_account_id_index', table_name='messages')
    op.create_index('messages_user_id_index', 'messages', ['user_id'], unique=False)
    op.create_index('messages_source_id_index', 'messages', ['source_id'], unique=False)
    op.create_index('messages_sent_at_index', 'messages', ['sent_at'], unique=False)
    op.create_index('messages_inbox_id_index', 'messages', ['inbox_id'], unique=False)
    op.create_index('messages_conversation_id_index', 'messages', ['conversation_id'], unique=False)
    op.create_index('messages_contact_id_index', 'messages', ['contact_id'], unique=False)
    op.create_index('messages_account_id_index', 'messages', ['account_id'], unique=False)
    # ### end Alembic commands ###
