"""Add total_rows and processed_rows  to import_jobs

Revision ID: b8af5e575119
Revises: a97914f920a6
Create Date: 2025-04-10 00:25:12.667034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8af5e575119'
down_revision: Union[str, None] = 'a97914f920a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_name_gin_trgm', table_name='contacts', postgresql_using='gin')
    op.create_index('ix_contacts_name_gin_trgm', 'contacts', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.add_column('import_jobs', sa.Column('total_rows', sa.Integer(), nullable=True))
    op.add_column('import_jobs', sa.Column('processed_rows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_jobs', 'processed_rows')
    op.drop_column('import_jobs', 'total_rows')
    op.drop_index('ix_contacts_name_gin_trgm', table_name='contacts', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_contacts_name_gin_trgm', 'contacts', ['phone_number'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
