"""add chunk_index

Revision ID: bd578b560387
Revises: 39677f86a2b5
Create Date: 2025-06-08 01:13:26.129057

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd578b560387"
down_revision: Union[str, None] = "39677f86a2b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge_chunks",
        sa.Column("chunk_index", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_index(
        "ix_chunk_document_id_chunk_index",
        "knowledge_chunks",
        ["document_id", "chunk_index"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chunk_document_id_chunk_index", table_name="knowledge_chunks")
    op.drop_column("knowledge_chunks", "chunk_index")
    # ### end Alembic commands ###
