"""Add evolution instance model

Revision ID: c1ecc9564dce
Revises: 9955fb5cc716
Create Date: 2025-03-31 23:26:20.815563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ecc9564dce'
down_revision: Union[str, None] = '9955fb5cc716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evolution_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_name', sa.String(length=255), nullable=False),
    sa.Column('shared_api_url', sa.String(length=512), nullable=False),
    sa.Column('logical_token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('webhook_url', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CREATED', 'CONNECTED', 'DISCONNECTED', 'ERROR', name='evolutioninstancestatus'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_name', name='uq_evolution_instances_instance_name')
    )
    op.create_index('ix_evolution_instances_account_id', 'evolution_instances', ['account_id'], unique=False)
    op.create_index('ix_evolution_instances_instance_name', 'evolution_instances', ['instance_name'], unique=False)
    op.create_index('ix_evolution_instances_status', 'evolution_instances', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evolution_instances_status', table_name='evolution_instances')
    op.drop_index('ix_evolution_instances_instance_name', table_name='evolution_instances')
    op.drop_index('ix_evolution_instances_account_id', table_name='evolution_instances')
    op.drop_table('evolution_instances')
    # ### end Alembic commands ###
