"""add plan tier to account model

Revision ID: c5b5da97ca5e
Revises: 4d0e498b724d
Create Date: 2025-05-24 14:31:23.733158

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c5b5da97ca5e"
down_revision: Union[str, None] = "4d0e498b724d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DB_ENUM_VALUES = ("free", "basic", "pro", "enterprise")
PLAN_TIER_STATUS_ENUM_NAME = "account_plan_tier_enum"


def upgrade() -> None:
    db_account_plan_tier_enum = postgresql.ENUM(
        *DB_ENUM_VALUES, name=PLAN_TIER_STATUS_ENUM_NAME
    )
    db_account_plan_tier_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column(
            "active_plan_tier",
            sa.Enum(
                "FREE", "BASIC", "PRO", "ENTERPRISE", name="account_plan_tier_enum"
            ),
            nullable=True,
            comment="Current active plan tier for the account (e.g., free, basic, pro)",
        ),
    )
    op.create_index(
        op.f("ix_accounts_active_plan_tier"),
        "accounts",
        ["active_plan_tier"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_accounts_active_plan_tier"), table_name="accounts")
    op.drop_column("accounts", "active_plan_tier")
    # ### end Alembic commands ###
    db_account_plan_tier_enum.drop(op.get_bind(), checkfirst=True)
