"""Update Inbox model with channel_details and non-nullable type

Revision ID: c8b91e8bb432
Revises: 1b205b5284d2
Create Date: 2025-03-31 18:51:28.464660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8b91e8bb432'
down_revision: Union[str, None] = '1b205b5284d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inboxes', sa.Column('channel_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('inboxes', 'channel_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inboxes', 'channel_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('inboxes', 'channel_details')
    # ### end Alembic commands ###
