"""Add simulation entity IDs to Account model

Revision ID: ce98cb1386bf
Revises: 82fa6c556fae
Create Date: 2025-04-29 01:19:40.777215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce98cb1386bf'
down_revision: Union[str, None] = '82fa6c556fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('simulation_inbox_id', sa.UUID(), nullable=True))
    op.add_column('accounts', sa.Column('simulation_contact_id', sa.UUID(), nullable=True))
    op.add_column('accounts', sa.Column('simulation_conversation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_accounts_simulation_inbox_id'), 'accounts', ['simulation_inbox_id'], unique=False)
    op.create_foreign_key('fk_account_sim_inbox', 'accounts', 'inboxes', ['simulation_inbox_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_account_sim_contact', 'accounts', 'contacts', ['simulation_contact_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_account_sim_convo', 'accounts', 'conversations', ['simulation_conversation_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_account_sim_convo', 'accounts', type_='foreignkey')
    op.drop_constraint('fk_account_sim_contact', 'accounts', type_='foreignkey')
    op.drop_constraint('fk_account_sim_inbox', 'accounts', type_='foreignkey')
    op.drop_index(op.f('ix_accounts_simulation_inbox_id'), table_name='accounts')
    op.drop_column('accounts', 'simulation_conversation_id')
    op.drop_column('accounts', 'simulation_contact_id')
    op.drop_column('accounts', 'simulation_inbox_id')
    # ### end Alembic commands ###
