"""Init LangGraph checkpoints schema

Revision ID: d38e48325068
Revises: 7dc4950abc22
Create Date: 2025-04-30 00:06:22.298496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from langgraph.checkpoint.postgres import PostgresSaver
from psycopg import Connection

from app.config import get_settings, Settings

settings: Settings = get_settings()
DB_URI = settings.DATABASE_URL.replace("+asyncpg", "")

# revision identifiers, used by Alembic.
revision: str = "d38e48325068"
down_revision: Union[str, None] = "7dc4950abc22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with Connection.connect(DB_URI, autocommit=True) as conn:
        saver = PostgresSaver(conn)
        saver.setup()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("checkpoints_thread_id_idx", table_name="checkpoints")

    # Dropar tabelas em ordem inversa
    op.drop_table("checkpoint_writes")
    op.drop_table("checkpoint_blobs")
    op.drop_table("checkpoints")
    op.drop_table("checkpoint_migrations")
    # ### end Alembic commands ###
