"""Change persona_definition to persona_id

Revision ID: e5495de9b66c
Revises: 3aed2d485d9a
Create Date: 2025-05-02 23:35:23.168985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e5495de9b66c"
down_revision: Union[str, None] = "3aed2d485d9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_personas_contact_id"), "personas", ["contact_id"], unique=True
    )
    op.create_index(
        op.f("ix_personas_persona_id"), "personas", ["persona_id"], unique=False
    )
    op.create_index(
        op.f("ix_personas_simulation_contact_identifier"),
        "personas",
        ["simulation_contact_identifier"],
        unique=False,
    )
    op.add_column("simulations", sa.Column("persona_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_simulations_persona_id"), "simulations", ["persona_id"], unique=False
    )
    op.create_foreign_key(
        None, "simulations", "personas", ["persona_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("simulations", "persona_definition")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulations",
        sa.Column(
            "persona_definition",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "simulations", type_="foreignkey")
    op.drop_index(op.f("ix_simulations_persona_id"), table_name="simulations")
    op.drop_column("simulations", "persona_id")
    op.drop_index(
        op.f("ix_personas_simulation_contact_identifier"), table_name="personas"
    )
    op.drop_index(op.f("ix_personas_persona_id"), table_name="personas")
    op.drop_index(op.f("ix_personas_contact_id"), table_name="personas")

    # ### end Alembic commands ###
