"""Add sales_focus to company profile

Revision ID: e89b307cfcb4
Revises: 1063f8d5f5d9
Create Date: 2025-06-28 20:49:18.116770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e89b307cfcb4'
down_revision: Union[str, None] = '1063f8d5f5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profiles', sa.Column('sales_focus', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_profiles', 'sales_focus')
    # ### end Alembic commands ###
