"""migrate ids to uuid

Revision ID: 1c4dc0c015bf
Revises: 74fea0132fcb
Create Date: 2025-03-28 14:00:33.806345
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1c4dc0c015bf"
down_revision: Union[str, None] = "74fea0132fcb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "access_tokens",
        "owner_id",
        existing_type=sa.BIGINT(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="owner_id::uuid",
    )
    op.alter_column(
        "access_tokens",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column(
        "account_users",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column(
        "account_users",
        "account_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="account_id::uuid",
    )
    op.alter_column(
        "account_users",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="user_id::uuid",
    )
    op.alter_column(
        "account_users",
        "inviter_id",
        existing_type=sa.BIGINT(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="inviter_id::uuid",
    )
    op.alter_column(
        "accounts",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column(
        "agent_bot_inboxes",
        "account_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="account_id::uuid",
    )
    op.alter_column(
        "agent_bot_inboxes",
        "inbox_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="inbox_id::uuid",
    )
    op.alter_column(
        "agent_bot_inboxes",
        "agent_bot_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="agent_bot_id::uuid",
    )
    op.alter_column(
        "agent_bot_inboxes",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column(
        "agent_bots",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column(
        "contact_inboxes",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column(
        "contact_inboxes",
        "contact_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="contact_id::uuid",
    )
    op.alter_column(
        "contact_inboxes",
        "inbox_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="inbox_id::uuid",
    )
    op.alter_column(
        "contacts",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column(
        "contacts",
        "account_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="account_id::uuid",
    )
    op.alter_column(
        "conversations",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column(
        "conversations",
        "account_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="account_id::uuid",
    )
    op.alter_column(
        "conversations",
        "inbox_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="inbox_id::uuid",
    )
    op.alter_column(
        "conversations",
        "contact_inbox_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="contact_inbox_id::uuid",
    )
    op.alter_column(
        "conversations",
        "assignee_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="assignee_id::uuid",
    )
    op.alter_column(
        "events",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column(
        "events",
        "account_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="account_id::uuid",
    )
    op.alter_column(
        "events",
        "inbox_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="inbox_id::uuid",
    )
    op.alter_column(
        "events",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="user_id::uuid",
    )
    op.alter_column(
        "events",
        "conversation_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="conversation_id::uuid",
    )
    op.alter_column(
        "inbox_members",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column(
        "inbox_members",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="user_id::uuid",
    )
    op.alter_column(
        "inbox_members",
        "inbox_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="inbox_id::uuid",
    )
    op.alter_column(
        "inboxes",
        "account_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="account_id::uuid",
    )
    op.alter_column(
        "messages",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column(
        "messages",
        "account_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="account_id::uuid",
    )
    op.alter_column(
        "messages",
        "inbox_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="inbox_id::uuid",
    )
    op.alter_column(
        "messages",
        "conversation_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="conversation_id::uuid",
    )
    op.alter_column(
        "messages",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="user_id::uuid",
    )
    op.alter_column(
        "messages",
        "contact_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="contact_id::uuid",
    )
    op.alter_column(
        "subscriptions",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column(
        "subscriptions",
        "account_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="account_id::uuid",
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column(
        "webhooks",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column(
        "webhooks",
        "account_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="account_id::uuid",
    )
    op.alter_column(
        "webhooks",
        "inbox_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="inbox_id::uuid",
    )
    op.alter_column(
        "webhooks",
        "webhook_type",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
