"""add profile_picture_url to contacts

Revision ID: 95712824e3f7
Revises: 895e414822f6
Create Date: 2025-03-26 01:04:11.390581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95712824e3f7'
down_revision: Union[str, None] = '895e414822f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('profile_picture_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'profile_picture_url')
    # ### end Alembic commands ###
