"""Initial migration

Revision ID: d95bdcd2f6f3
Revises: 
Create Date: 2025-03-24 13:08:19.146574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95bdcd2f6f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_tokens',
    sa.Column('owner_type', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('scopes', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='access_tokens_token_unique')
    )
    op.create_index('access_tokens_owner_type_owner_id_index', 'access_tokens', ['owner_type', 'owner_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_bots',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('outgoing_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.String(length=255), nullable=False),
    sa.Column('reset_password_token', sa.String(length=255), nullable=True),
    sa.Column('reset_password_sent_at', sa.DateTime(), nullable=True),
    sa.Column('remember_created_at', sa.DateTime(), nullable=True),
    sa.Column('sign_in_count', sa.Integer(), nullable=False),
    sa.Column('current_sign_in_at', sa.DateTime(), nullable=True),
    sa.Column('last_sign_in_at', sa.DateTime(), nullable=True),
    sa.Column('current_sign_in_ip', sa.String(length=255), nullable=True),
    sa.Column('last_sign_in_ip', sa.String(length=255), nullable=True),
    sa.Column('confirmation_token', sa.String(length=255), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmation_sent_at', sa.DateTime(), nullable=True),
    sa.Column('unconfirmed_email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tokens', sa.JSON(), nullable=True),
    sa.Column('pubsub_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'uid', name='users_provider_uid_unique'),
    sa.UniqueConstraint('pubsub_token', name='users_pubsub_token_unique'),
    sa.UniqueConstraint('reset_password_token', name='users_reset_password_token_unique')
    )
    op.create_index('users_email_index', 'users', ['email'], unique=False)
    op.create_table('account_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'AGENT', 'VIEWER', 'BOT', name='userrole'), nullable=True),
    sa.Column('inviter_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'user_id', name='account_users_account_id_user_id_unique')
    )
    op.create_index('account_users_account_id_index', 'account_users', ['account_id'], unique=False)
    op.create_index('account_users_user_id_index', 'account_users', ['user_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('pubsub_token', sa.String(length=255), nullable=True),
    sa.Column('identifier', sa.String(length=255), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('additional_attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'identifier', name='contacts_account_id_identifier_unique'),
    sa.UniqueConstraint('email', 'account_id', name='contacts_email_account_id_unique'),
    sa.UniqueConstraint('pubsub_token', name='contacts_pubsub_token_unique')
    )
    op.create_index('contacts_account_id_index', 'contacts', ['account_id'], unique=False)
    op.create_table('inboxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel_type', sa.String(length=255), nullable=True),
    sa.Column('enable_auto_assignment', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('inboxes_account_id_index', 'inboxes', ['account_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('pricing_version', sa.String(length=255), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('billing_plan', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('payment_source_added', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_bot_inboxes',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('inbox_id', sa.Integer(), nullable=True),
    sa.Column('agent_bot_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['agent_bot_id'], ['agent_bots.id'], ),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_inboxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('inbox_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inbox_id', 'source_id', name='contact_inboxes_inbox_id_source_id_unique')
    )
    op.create_index('contact_inboxes_source_id_index', 'contact_inboxes', ['source_id'], unique=False)
    op.create_table('inbox_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('inbox_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'inbox_id', name='inbox_members_user_id_inbox_id_unique')
    )
    op.create_index('inbox_members_inbox_id_index', 'inbox_members', ['inbox_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('inbox_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('webhook_type', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'url', name='webhooks_account_id_url_unique')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('inbox_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('contact_inbox_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('display_id', sa.Integer(), nullable=False),
    sa.Column('user_last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('agent_last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('additional_attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['contact_inbox_id'], ['contact_inboxes.id'], ),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'display_id', name='conversations_account_id_display_id_unique')
    )
    op.create_index('conversations_account_id_index', 'conversations', ['account_id'], unique=False)
    op.create_index('conversations_contact_inbox_id_index', 'conversations', ['contact_inbox_id'], unique=False)
    op.create_table('events',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('inbox_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('events_account_id_index', 'events', ['account_id'], unique=False)
    op.create_index('events_created_at_index', 'events', ['created_at'], unique=False)
    op.create_index('events_inbox_id_index', 'events', ['inbox_id'], unique=False)
    op.create_index('events_name_index', 'events', ['name'], unique=False)
    op.create_index('events_user_id_index', 'events', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('inbox_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('content_attributes', sa.JSON(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('messages_account_id_index', 'messages', ['account_id'], unique=False)
    op.create_index('messages_contact_id_index', 'messages', ['contact_id'], unique=False)
    op.create_index('messages_conversation_id_index', 'messages', ['conversation_id'], unique=False)
    op.create_index('messages_inbox_id_index', 'messages', ['inbox_id'], unique=False)
    op.create_index('messages_source_id_index', 'messages', ['source_id'], unique=False)
    op.create_index('messages_user_id_index', 'messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('messages_user_id_index', table_name='messages')
    op.drop_index('messages_source_id_index', table_name='messages')
    op.drop_index('messages_inbox_id_index', table_name='messages')
    op.drop_index('messages_conversation_id_index', table_name='messages')
    op.drop_index('messages_contact_id_index', table_name='messages')
    op.drop_index('messages_account_id_index', table_name='messages')
    op.drop_table('messages')
    op.drop_index('events_user_id_index', table_name='events')
    op.drop_index('events_name_index', table_name='events')
    op.drop_index('events_inbox_id_index', table_name='events')
    op.drop_index('events_created_at_index', table_name='events')
    op.drop_index('events_account_id_index', table_name='events')
    op.drop_table('events')
    op.drop_index('conversations_contact_inbox_id_index', table_name='conversations')
    op.drop_index('conversations_account_id_index', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('webhooks')
    op.drop_index('inbox_members_inbox_id_index', table_name='inbox_members')
    op.drop_table('inbox_members')
    op.drop_index('contact_inboxes_source_id_index', table_name='contact_inboxes')
    op.drop_table('contact_inboxes')
    op.drop_table('agent_bot_inboxes')
    op.drop_table('subscriptions')
    op.drop_index('inboxes_account_id_index', table_name='inboxes')
    op.drop_table('inboxes')
    op.drop_index('contacts_account_id_index', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('account_users_user_id_index', table_name='account_users')
    op.drop_index('account_users_account_id_index', table_name='account_users')
    op.drop_table('account_users')
    op.drop_index('users_email_index', table_name='users')
    op.drop_table('users')
    op.drop_table('agent_bots')
    op.drop_table('accounts')
    op.drop_index('access_tokens_owner_type_owner_id_index', table_name='access_tokens')
    op.drop_table('access_tokens')
    # ### end Alembic commands ###
